name: Snyk Security Scan

on:
  push:
    branches: [ main, main-beta ]

env:
  node-version: 22.x

concurrency:
  group: snyk-${{ github.ref }}
  cancel-in-progress: true

jobs:
  snyk:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v6

      - name: Set up Node v${{ env.node-version }}
        uses: actions/setup-node@v6
        with:
          cache: 'npm'
          node-version: ${{ env.node-version }}

      - name: Install dependencies
        run: npm ci

      - name: Run Snyk to code test
        uses: snyk/actions/node@master
        continue-on-error: true
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          command: code test
          args: --all-projects --sarif-file-output=snyk.sarif --clear-cache

      - name: Upload result to GitHub Code Scanning
        uses: github/codeql-action/upload-sarif@v4
        with:
          sarif_file: snyk.sarif
